---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: kino
description: iwakura's personal Kinoite image
base-image: ghcr.io/ublue-os/kinoite-main
image-version: latest

modules:
  - type: dnf
    remove:
      packages:
        # software center -> replaced by Bazaar
        - plasma-discover
        - plasma-discover-libs
        - plasma-discover-flatpak
        - plasma-discover-kns
        - plasma-discover-notifier
        - plasma-discover-rpm-ostree
        # bundled apps not wanted
        - krfb
        - krfb-libs
        - ark
        - ark-libs
        - firefox
        - firefox-langpacks
        - kfind
        - spectacle
        - filelight
        - kcharselect

  - type: default-flatpaks
    configurations:
      - notify: true
        scope: system
        remove:
          - org.kde.elisa
          - org.kde.gwenview
          - org.kde.kcalc
          - org.kde.kolourpaint
          - org.kde.krdc
          - org.kde.okular
          - org.kde.qrca
          - org.kde.skanpage
        install:
          - io.github.kolunmi.Bazaar
          - io.github.tanaybhomia.Whisp
          - com.discordapp.Discord
          - com.valvesoftware.Steam
          - it.mijorus.gearlever
      - scope: user

  - type: signing
